[theme]
primaryColor = "#4F8BF9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = true

# Use legacy dataframe serialization to avoid hard dependency on pyarrow
dataFrameSerialization = "legacy"
